# Generated by Django 4.0.3 on 2022-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='id',
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='pasaporte',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='n_vuelo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
