# Generated by Django 4.0.3 on 2022-03-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_remove_pasajero_id_remove_vuelo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='hora_salida',
            new_name='salida',
        ),
    ]
