# Generated by Django 4.0.3 on 2022-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_rename_hora_salida_vuelo_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comida', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
                ('opinion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Montanas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('dificultad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Aeropuerto',
        ),
        migrations.DeleteModel(
            name='Equipaje',
        ),
        migrations.DeleteModel(
            name='Pasajero',
        ),
        migrations.DeleteModel(
            name='Vuelo',
        ),
    ]
