# Generated by Django 4.0.3 on 2022-03-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0004_comidas_montanas_viajes_delete_aeropuerto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
