# Generated by Django 4.0.3 on 2022-03-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0007_alter_viajes_destino_alter_viajes_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajes',
            old_name='año',
            new_name='anio',
        ),
    ]
